<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petrinet" nsURI="http://petrinet" nsPrefix="petrinet">
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcs" upperBound="-1" eType="#//Arc"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noeuds" upperBound="-1"
        eType="#//Noeud" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Noeud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcArrivant" upperBound="-1"
        eType="#//Arc" eOpposite="#//Arc/cible"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcPartant" upperBound="-1"
        eType="#//Arc" eOpposite="#//Arc/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Noeud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbJeton" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Noeud"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arc">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="poids" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeArc" lowerBound="1"
        eType="#//ArcType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cible" lowerBound="1" eType="#//Noeud"
        eOpposite="#//Noeud/arcArrivant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Noeud" eOpposite="#//Noeud/arcPartant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArcType">
    <eLiterals name="normalArc" literal="normalArc"/>
    <eLiterals name="readArc" value="1"/>
    <eLiterals name="inhibiteurArc" value="2"/>
  </eClassifiers>
</ecore:EPackage>
